apps/departamentos/urls.py
from django.urls import path
from .views import DepartamentosList, DepartamentoNovo, DepartamentoEdit, Departamentodelete

# from .views import NovoClienteView, TodosClientesView, ExcluirClienteView, DetalheClienteView, EditarClienteView, \
#     IntroClienteView, GuiaClienteView
#


app_name = 'departamentos'

urlpatterns = [

    path('list', DepartamentosList.as_view(), name="list_departamentos"),
    path('novo', DepartamentoNovo.as_view(), name="create_departamentos"),
    path('editar/<int:pk>/', DepartamentoEdit.as_view(), name="update_departamentos"),
    path('deletar/<int:pk>/', Departamentodelete.as_view(), name="delete_departamentos"),


]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('apps.core.urls')),
                  path('funcionarios/', include('apps.funcionarios.urls')),
                  path('empresa/', include('apps.empresas.urls')),
                  path('horas-extras/', include('apps.registro_hora_extra.urls')),
                  path('departamentos/', include('apps.departamentos.urls')),
                  path('documentos/', include('apps.documentos.urls')),
                  # path('/', include('apps.core.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

                  path('admin/', admin.site.urls)
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/departamentos/models.py
from django.db import models


# Create your models here.
from django.urls import reverse

from apps.empresas.models import Empresa


class Departamento(models.Model):
    nome = models.CharField(max_length=70)
    empresa = models.ForeignKey(Empresa, on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse('departamentos:list_departamentos')

    def __str__(self):
        return self.nome

apps/departamentos/views.py
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.departamentos.models import Departamento
from apps.funcionarios.models import Funcionario


class DepartamentoNovo(CreateView):
    model = Departamento
    fields = ['nome']

    def form_valid(self, form):
        departamento = form.save(commit=False)
        departamento.empresa = self.request.user.funcionario.empresa
        departamento.save()
        return super(DepartamentoNovo, self).form_valid(form)


class DepartamentosList(ListView):
    model = Departamento

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Departamento.objects.filter(empresa=empresa_logada)


class DepartamentoEdit(UpdateView):
    model = Departamento
    fields = ['nome']


class Departamentodelete(DeleteView):
    model = Departamento
    success_url = reverse_lazy('departamentos:list_departamentos')

apps/departamentos/templates/departamentos/departamento_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}
{% block  main %}

<form method="post">
{% csrf_token %}
    {{ form|bootstrap }}
    <h1 class="justify-content-around">Você Deseja mesmo deletar o departamento {{ obj }} ?</h1>

    {{ form }}


<button type="submit" class="btn btn-danger" >Confirmar</button>
</form>

{% endblock %}

apps/departamentos/templates/departamentos/departamento_form.html
{% extends 'base.html' %}
{% load static %}
{% block  main %}

<form method="post">
{% csrf_token %}
    {{ form }}

<button type="submit" class="btn-primary" >Salvar</button>
</form>

{% endblock %}

apps/departamentos/templates/departamentos/departamento_list.html
{% extends 'base.html' %}

{% block  main %}
    <br> {% for departamento in  object_list %}
    <a href="{% url 'departamentos:update_departamentos' departamento.id %}">
        {{ departamento }}</a>
    <a href="{% url 'departamentos:delete_departamentos' departamento.id %}">Deletar</a><br>
{% endfor %}
    <a href="{% url 'departamentos:create_departamentos' %}" class="btn btn-info"> Novo</a>
{% endblock %}