apps/registro_hora_extra/urls.py
from django.urls import path
from .views import HoraExtraList, HoraExtraEdit, FuncionarioDelete, HoraExtraNovo

# from .views import NovoClienteView, TodosClientesView, ExcluirClienteView, DetalheClienteView, EditarClienteView, \
#     IntroClienteView, GuiaClienteView
#


app_name = 'hora_extra'

urlpatterns = [

    path('', HoraExtraList.as_view(), name="list_hora_extra"),
    path('editar/<int:pk>/', HoraExtraEdit.as_view(), name="update_hora_extra"),
    path('novo/', HoraExtraNovo.as_view(), name="create_hora_extra"),
    path('deletar/<int:pk>/', FuncionarioDelete.as_view(), name="delete_hora_extra"),

]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('apps.core.urls')),
                  path('funcionarios/', include('apps.funcionarios.urls')),
                  path('empresa/', include('apps.empresas.urls')),
                  path('horas-extras/', include('apps.registro_hora_extra.urls')),
                  path('departamentos/', include('apps.departamentos.urls')),
                  path('documentos/', include('apps.documentos.urls')),
                  # path('/', include('apps.core.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

                  path('admin/', admin.site.urls)
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


# Create your models here.
class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)

    def get_absolute_url(self):
        return reverse('hora_extra:update_hora_extra', args=[self.id])

    def __str__(self):
        return self.motivo

apps/registro_hora_extra/forms.py
from django.forms import ModelForm
from .models import RegistroHoraExtra
from apps.funcionarios.models import Funcionario


class RegistroHoraExtraForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(RegistroHoraExtraForm, self).__init__(*args, **kwargs)
        self.fields['funcionario'].queryset = Funcionario.objects.filter(
            empresa=user.funcionario.empresa)

    class Meta:
        model = RegistroHoraExtra
        fields = ['motivo', 'funcionario', 'horas']

apps/registro_hora_extra/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from apps.funcionarios.models import Funcionario
from apps.registro_hora_extra.models import RegistroHoraExtra


class HoraExtraList(ListView):
    model = RegistroHoraExtra

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return RegistroHoraExtra.objects.filter(funcionario__empresa=empresa_logada)


class HoraExtraEdit(UpdateView):
    model = RegistroHoraExtra
    fields = ['motivo', 'funcionario', 'horas']


class FuncionarioDelete(DeleteView):
    model = RegistroHoraExtra
    success_url = reverse_lazy('hora_extra:list_hora_extra')

class HoraExtraNovo(CreateView):
    model = RegistroHoraExtra
    form_class = RegistroHoraExtra

    def get_form_kwargs(self):
        kwargs = super(HoraExtraNovo, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

apps/registro_hora_extra/templates/registro_hora_extra/registrohoraextra_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}
{% block  main %}

    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <h1 class="justify-content-around">Você Deseja mesmo deletar a hora extra {{  object }} ?</h1>

        {{ form }}


        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>

{% endblock %}

apps/registro_hora_extra/templates/registro_hora_extra/registrohoraextra_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load static %}
{% block  main %}

    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <br>


        <button type="submit" class="btn btn-primary">Salvar</button>
        {% if object %}
            <a href="{% url 'hora_extra:delete_hora_extra' object.id %}" class="btn btn-danger">
                Deletar
            </a>
        {% endif %}

    </form><br>


{% endblock %}

apps/registro_hora_extra/templates/registro_hora_extra/registrohoraextra_list.html
{% extends 'base.html' %}

{% block  main %}
    Banco de Horas
    <br>
    {% for registro_re in  object_list %}

        <a href=" {% url 'hora_extra:update_hora_extra' registro_re.id %}">
            {{ registro_re }}
        </a>

            <a href="{% url 'hora_extra:delete_hora_extra' registro_re.id %}">
                Deletar
            </a>
        <br>


    {% endfor %}
    {% if not object_list %}
        <h3> Não existem registros de hora extra no banco de dados</h3>
    {% endif %}

    <a href="{% url 'hora_extra:create_hora_extra' %}" class="btn btn-primary">
        Novo
    </a>

{% endblock %}